#!/usr/local/python/bin/python
"""
Utility to join an nghomelimits screen session
"""
import os
import socket
sn = 'nghomelimits'
hn = socket.gethostname().split('-')[-2:]
if 'das' in hn:
    os.system('screen -xr {}'.format(sn))
else:
    print('This command only works on DAS machines')
