#!/usr/local/python/bin/python
"""
Utility to help multiple talon screen sessions
"""
import os
import socket
hn = ''.join(socket.gethostname().split('-')[-2:]) + '_tal'
os.system('screen -xr {}'.format(hn))
